add_newline = false

format = """
$username\
$hostname\
$directory\
$character
"""

[username]
show_always = true
style_user = "bold green"
style_root = "bold red"
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "bold green"
format = '@[$hostname]($style):'

[directory]
style = "bold blue"
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"
format = '[$path]($style)'

[character]
success_symbol = '[\$](bold white) '
error_symbol = '[\$](bold red) '
vimcmd_symbol = '[\$](bold white) '
